{{- range $env, $config := .Values.envList }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ $.Values.serviceName }}-{{ $env }}"
  namespace: {{ $.Values.namespace }}
  labels:
    entity-id: {{ $.Values.serviceName }}
spec:
  project: {{ $.Values.project }}
  source:
    path: {{ $config.path }}
    repoURL: "{{ $config.repo }}"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $config.namespace }}
  syncPolicy:
    automated:
      selfHeal: true
---
{{- end }}