{{ if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: "{{ .Values.namespace }}-{{ .Values.envName }}"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: {{ .Values.service.port }}
            path: /{{ .Values.appName }}/{{ .Values.envName }}(/|$)(.*)
            pathType: ImplementationSpecific
{{ end }}